### ISSUE TITLE
Terms

### ISSUE THREAD

**Issue by xamgore** [xamgore/au-conspectus#6]
Термины как в википедии: всплывающие определения.

Александра, если у тебя нет других задач, попробуй всё же сделать подсветку термов по всему конспекту, а потом с игнорированием окончаний (для этого нужно найти словарь или корпус русского / английского языка). Можно объединиться с Димой и пописать что-нибудь на питоне — там много библиотек для NLP.

**Comment by xamgore** [comment]
@demiurg906 хороший пример почему это нужно:

В конспекте есть терм `(для списков смежности)`, твой скрипт даёт полную дичь:

![image](https://user-images.githubusercontent.com/4586392/32359226-78903cea-c05d-11e7-8446-8371e9770fa8.png)

Что в принципе ожидаемо, потому что [поиск вики](https://ru.wikipedia.org/w/index.php?search=%28%D0%B4%D0%BB%D1%8F+%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%BE%D0%B2+%D1%81%D0%BC%D0%B5%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D0%B8%29&title=%D0%A1%D0%BB%D1%83%D0%B6%D0%B5%D0%B1%D0%BD%D0%B0%D1%8F:%D0%9F%D0%BE%D0%B8%D1%81%D0%BA&go=%D0%9F%D0%B5%D1%80%D0%B5%D0%B9%D1%82%D0%B8&searchToken=1owt1sqvldts5o944cqgc9uw1) предлагает матрицу смежности на первое место. Всё-таки, надо приводить фразы в нейтральную форму.

**Comment by demiurg906** [comment]
Мы вроде это закрыли
